apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dtfk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0054-tenant/tkrw-pr714-0075-0054-app/devfile-sample-dtfk@sha256:798aa1eab4a2a654d5879cf40d55b13c735482023426f89d88b9a2bd96061773
        name: my-nodejs
        resources: {}
status: {}
